services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paginou-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - paginou-network

  nginx:
    image: nginx:alpine
    container_name: paginou-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - paginou-network

  mysql:
    image: mysql:8.0
    container_name: paginou-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - paginou-mysql:/var/lib/mysql
    networks:
      - paginou-network

  redis:
    image: redis:alpine
    container_name: paginou-redis
    restart: unless-stopped
    networks:
      - paginou-network

networks:
  paginou-network:
    driver: bridge

volumes:
  paginou-mysql:
    driver: local 